import Head from 'next/head'
import GameBoard from '@/components/GameBoard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Noughts & Crosses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>     
          <h1>Noughts & Crosses</h1>
          <GameBoard/>
      </main>
    </>
  )
}
